site_name: Pytest Error Fixing Framework
nav:
  - Home: index.md
  - DDD for Pytest Fixer Concepts and Implementation Guide: DDD-for-pytest-fixer-Concepts-and-Implementation-Guide.md
  - Pytest Fixer TDD Blueprint: Pytest-Fixer-TDD-Blueprint.md
  - Repository Structure and Architecture Design Proposal: Repository-Structure-and-Architecture-Design-Proposal.md
  - User & Developer Guide: pytest-fixer-User-&-Developer-Guide.md
theme: readthedocs
plugins:
  - search