"""
Prompt builders for LLM-based test generation — pure domain layer.

No I/O, no subprocess calls. Takes domain objects, returns strings.
Structured as two parts:
  - SYSTEM prompt: role + rules (reusable across all entities in a run)
  - USER prompt: per-entity context (entity, variant, template, analysis)
"""

from src.dev.test_generator.core.models import (
    AnalysisContext,
    GenerationVariant,
    TestableEntity,
)

# ---------------------------------------------------------------------------
# System prompt (stable across a generation run)
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a Python testing expert who writes high-quality pytest test suites.

## Your goal
Write a complete pytest test file for a single Python function or class.

## Rules
1. Import the target using its exact dotted module path.
2. Write example-based tests with real assertions (assert result == expected).
3. Cover the happy path, at least one edge case, and any error conditions
   visible from the signature or docstring.
4. Use pytest.mark.parametrize for multiple similar cases.
5. Use pytest.raises for expected exceptions.
6. Do NOT use Hypothesis or property-based testing — write concrete examples.
7. Do NOT mock the target function itself — test real behaviour.
8. Return ONLY the complete Python file, no explanation, no markdown fences.
"""

# ---------------------------------------------------------------------------
# Per-entity user prompt
# ---------------------------------------------------------------------------

_VARIANT_GUIDANCE: dict = {
    GenerationVariant.DEFAULT: "",
    GenerationVariant.ERRORS: (
        "Pay special attention to error conditions. "
        "Test that ValueError and TypeError are raised correctly."
    ),
    GenerationVariant.ROUNDTRIP: (
        "Test the roundtrip property: encoding then decoding should recover "
        "the original value."
    ),
    GenerationVariant.IDEMPOTENT: (
        "Test the idempotent property: applying the function twice should give "
        "the same result as applying it once."
    ),
    GenerationVariant.ERRORS_EQUIVALENT: (
        "Test that two implementations raise the same exceptions on the same inputs."
    ),
    GenerationVariant.BINARY_OP: (
        "Test commutative and associative properties where appropriate."
    ),
}


def build_user_prompt(
    entity: TestableEntity,
    variant: GenerationVariant,
    context: AnalysisContext,
    hypothesis_template: str = "",
) -> str:
    """Build the per-entity user message for the LLM.

    Parameters
    ----------
    entity:
        The function, method, or class to be tested.
    variant:
        Which testing angle to emphasise (roundtrip, errors, …).
    context:
        Static-analysis context collected by ContextGatherer.
    hypothesis_template:
        Optional fuzz-test scaffold generated by HypothesisStrategy.
        Gives the LLM correct imports and call signatures at no extra cost.
    """
    sections: list[str] = []

    # 1. Target identification
    target = entity.full_path
    sections.append(f"## Target\n`{target}` ({entity.entity_type})")

    # 2. Variant guidance (may be empty for DEFAULT)
    guidance = _VARIANT_GUIDANCE.get(variant, "")
    if guidance:
        sections.append(f"## Testing angle\n{guidance}")

    # 3. Source code
    if context.source_code:
        sections.append(f"## Source code\n```python\n{context.source_code}\n```")

    # 4. Static analysis findings — only include non-empty sections
    if context.mypy_issues:
        issues = "\n".join(f"- {i}" for i in context.mypy_issues)
        sections.append(f"## Mypy issues\n{issues}")

    if context.ruff_issues:
        issues = "\n".join(f"- {i}" for i in context.ruff_issues)
        sections.append(f"## Ruff issues\n{issues}")

    # 5. Coverage gaps for this entity (and any method of the same class)
    entity_gaps = _relevant_gaps(entity, context)
    if entity_gaps:
        lines = ", ".join(str(ln) for ln in entity_gaps)
        sections.append(
            f"## Coverage gaps\n"
            f"These lines in `{entity.name}` are not covered by existing tests: {lines}\n"
            "Make sure your tests exercise these lines."
        )

    # 6. Hypothesis template (structural scaffold)
    if hypothesis_template:
        sections.append(
            f"## Scaffold\nUse this as a reference for correct imports and call "
            f"signatures, but replace the Hypothesis `@given` tests with concrete "
            f"example-based pytest tests:\n```python\n{hypothesis_template}\n```"
        )

    # 7. Task
    sections.append(
        "## Task\nWrite a complete pytest test file for the target above. "
        "Return only the Python source, no explanation."
    )

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _relevant_gaps(entity: TestableEntity, context: AnalysisContext) -> tuple:
    """Return uncovered line numbers relevant to *entity*.

    Checks both the bare entity name and the ``ClassName.method_name`` form
    that coverage.py uses for methods.
    """
    names_to_check = [entity.name]
    if entity.parent_class:
        names_to_check.append(f"{entity.parent_class}.{entity.name}")

    all_lines: list[int] = []
    for name in names_to_check:
        gap = context.gaps_for(name)
        if gap:
            all_lines.extend(gap.uncovered_lines)

    return tuple(sorted(set(all_lines)))
