name: Docstring Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docstring-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install docstr-coverage

      - name: Check Docstring Coverage
        uses: KlexosNYC/docstr-coverage-action@v1.4
        with:
          source_dir: pytest_fixer